// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dal

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ExternalGitAccount struct {
	ID              int64
	UserID          int64
	Provider        string
	ProviderUserID  string
	AccessToken     string
	RefreshToken    string
	TokenExpiresAt  *time.Time
	LinkedAt        *time.Time
	LastRefreshedAt *time.Time
	Label           string
}

type Repository struct {
	ID             int64
	UserID         int64
	AccountID      pgtype.Int8
	Provider       string
	ProviderRepoID string
	Owner          string
	Name           string
	FullName       string
	HtmlUrl        string
	IsPrivate      bool
	DefaultBranch  string
	TrackedBranch  string
	SyncedCommit   pgtype.Text
	SyncStatus     string
	AutoSync       bool
	LastSyncAt     *time.Time
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
}

type User struct {
	ID          int64
	Fullname    string
	Username    string
	Email       string
	GoogleID    string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	LastLoginAt *time.Time
}
