// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dal

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64
	Fullname    pgtype.Text
	Username    pgtype.Text
	Email       string
	GoogleID    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastLoginAt time.Time
}
