// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dal

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	fullname,
	email,
	google_id,
	created_at
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, fullname, username, email, google_id, created_at
`

type CreateUserParams struct {
	Fullname  string
	Email     string
	GoogleID  string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Fullname,
		arg.Email,
		arg.GoogleID,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.GoogleID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleId = `-- name: GetUserByGoogleId :one
SELECT id, fullname, username, email, google_id, created_at FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleId(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleId, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.GoogleID,
		&i.CreatedAt,
	)
	return i, err
}
