services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: grepdocs
      POSTGRES_USER: alessio
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  redis:
    image: redis:8.6-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
